##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

##
cuboid:
  table:
    dims: [2.2, 2.2, 0.2] # x, y, z
    pose: [0.0, 0.0, -0.1, 1, 0, 0, 0.0] 
    
  cube6:
    dims:
    - 0.1
    - 0.1
    - 0.5
    pose:
    - 0.0
    - -0.1
    - 0.25
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    color:
      - 1.0
      - 0.0
      - 0.0
      - 1.0
mesh:
  base_scene:
    pose: [0.5, 0.25, 0.0, 0.7071, 0.7071, 0, 0]
    file_path: "scene/box_man.obj"
    scale: [0.001, 0.001, 0.001]       
 
