# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
default_q: [
    0.0,-0.0002,0.0007,0.0002,-0.0003,0.0,0.0
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:
    - {name: finger_width_joint, rule: fixed, value: 0.0}
    - {name: left_inner_knuckle_joint, rule: fixed, value: -0.0}
    - {name: left_outer_knuckle_joint, rule: fixed, value: 1e-04}
    - {name: right_inner_knuckle_joint, rule: fixed, value: 0.0}
    - {name: right_outer_knuckle_joint, rule: fixed, value: -1e-04}
    - {name: left_inner_finger_joint, rule: fixed, value: 0.0}
    - {name: right_inner_finger_joint, rule: fixed, value: -0.0}

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - base_link:
    - "center": [0.0, 0.0, 0.082]
      "radius": 0.09
  - link1:
    - "center": [-0.0, 0.0, 0.053]
      "radius": 0.09
    - "center": [-0.0, 0.0, 0.199]
      "radius": 0.09
    - "center": [-0.0, 0.0, 0.126]
      "radius": 0.09
  - link2:
    - "center": [0.0, 0.055, 0.022]
      "radius": 0.09
    - "center": [0.0, 0.037, 0.138]
      "radius": 0.08
  - link3:
    - "center": [0.0, -0.0, 0.059]
      "radius": 0.08
    - "center": [-0.006, 0.022, 0.183]
      "radius": 0.08
  - link4:
    - "center": [0.0, 0.042, 0.017]
      "radius": 0.08
    - "center": [-0.013, 0.029, 0.129]
      "radius": 0.08
  - link5:
    - "center": [0.0, -0.0, 0.046]
      "radius": 0.07
    - "center": [0.0, -0.009, 0.185]
      "radius": 0.07
    - "center": [0.0, -0.005, 0.116]
      "radius": 0.07
  - link6:
    - "center": [0.0, 0.043, 0.012]
      "radius": 0.07
    - "center": [0.005, 0.067, 0.109]
      "radius": 0.075
  - link7:
    - "center": [0.0, 0.0, 0.03]
      "radius": 0.065
  - base_hand:
    - "center": [-0.0, -0.0, 0.038]
      "radius": 0.06
  - left_finger_tip:
    - "center": [-0.0, 0.003, 0.018]
      "radius": 0.015
  - right_finger_tip:
    - "center": [0.0, 0.005, 0.016]
      "radius": 0.015
  - right_finger_mount:
    - "center": [-0.0, 0.006, -0.009]
      "radius": 0.03
  - left_finger_mount:
    - "center": [0.0, -0.0, -0.009]
      "radius": 0.03
