# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
    - left_outer_knuckle_joint
    - right_outer_knuckle_joint
default_q: [
    -1e-04,-0.0004,0.0009,0.0003,-0.0005,0.0,0.0,-0.0,-0.0
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - base_link:
    - "center": [0.0, 0.0, 0.081]
      "radius": 0.07
  - link1:
    - "center": [-0.0, 0.0, 0.063]
      "radius": 0.07
    - "center": [0.0, -0.025, 0.223]
      "radius": 0.05
    - "center": [0.001, -0.014, 0.103]
      "radius": 0.06
    - "center": [0.0, -0.022, 0.176]
      "radius": 0.05
  - link2:
    - "center": [-0.0, 0.049, 0.0]
      "radius": 0.055
    - "center": [0.0, 0.036, 0.139]
      "radius": 0.06
    - "center": [0.0, 0.043, 0.068]
      "radius": 0.05
  - link3:
    - "center": [0.0, -0.0, 0.045]
      "radius": 0.05
    - "center": [-0.014, 0.016, 0.186]
      "radius": 0.05
    - "center": [-0.004, 0.009, 0.104]
      "radius": 0.05
  - link4:
    - "center": [0.0, 0.05, 0.0]
      "radius": 0.05
    - "center": [-0.019, 0.026, 0.138]
      "radius": 0.05
    - "center": [-0.012, 0.038, 0.069]
      "radius": 0.05
  - link5:
    - "center": [-0.001, 0.0, 0.044]
      "radius": 0.05
    - "center": [0.003, -0.024, 0.184]
      "radius": 0.05
    - "center": [0.001, -0.013, 0.108]
      "radius": 0.05
  - link6:
    - "center": [-0.001, 0.043, 0.0]
      "radius": 0.045
    - "center": [-0.002, 0.077, 0.107]
      "radius": 0.045
    - "center": [0.009, 0.05, 0.052]
      "radius": 0.04
    - "center": [0.033, 0.066, 0.11]
      "radius": 0.04
  - link7:
    - "center": [0.0, 0.0, 0.034]
      "radius": 0.04
  - base_hand:
    - "center": [-0.0, -0.0, 0.034]
      "radius": 0.04
  - left_outer_bar:
    - "center": [-0.0, -0.0, 0.027]
      "radius": 0.01
    - "center": [-0.0, -0.0, 0.043]
      "radius": 0.01
  - left_finger_mount:
    - "center": [-0.0, 0.001, 0.004]
      "radius": 0.008
    - "center": [-0.0, 0.008, 0.016]
      "radius": 0.007
  - left_finger_tip:
    - "center": [-0.0, -0.0, 0.005]
      "radius": 0.007
    - "center": [-0.0, 0.009, 0.007]
      "radius": 0.006
    - "center": [-0.0, 0.008, 0.016]
      "radius": 0.006
    - "center": [-0.0, 0.009, 0.027]
      "radius": 0.006
  - left_finger_plus:
    - "center": [0.006, -0.017, 0.003]
      "radius": 0.004
    - "center": [0.008, -0.016, 0.031]
      "radius": 0.003
    - "center": [0.006, -0.017, 0.011]
      "radius": 0.004
    - "center": [0.007, -0.017, 0.018]
      "radius": 0.003
    - "center": [0.007, -0.016, 0.025]
      "radius": 0.003
  - right_outer_bar:
    - "center": [0.0, 0.0, 0.026]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.045]
      "radius": 0.01
  - right_finger_mount:
    - "center": [0.0, 0.0, 0.007]
      "radius": 0.008
    - "center": [0.0, 0.01, 0.014]
      "radius": 0.008
  - right_finger_tip:
    - "center": [-0.002, 0.0, 0.003]
      "radius": 0.008
    - "center": [-0.001, 0.008, 0.006]
      "radius": 0.006
    - "center": [-0.0, 0.009, 0.016]
      "radius": 0.006
    - "center": [-0.001, 0.008, 0.023]
      "radius": 0.006
  - right_finger_plus:
    - "center": [0.005, -0.017, 0.004]
      "radius": 0.004
    - "center": [0.004, -0.016, 0.03]
      "radius": 0.003
    - "center": [0.004, -0.017, 0.011]
      "radius": 0.004
    - "center": [0.004, -0.017, 0.018]
      "radius": 0.003
    - "center": [0.004, -0.016, 0.024]
      "radius": 0.003
