# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

api_version: 1.0

# Defines the generalized coordinates. Each generalized coordinate is assumed
# to have an entry in the URDF.
# Lula will only use these joints to control the robot position.
cspace:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    - joint7
    - left_outer_knuckle_joint
    - right_outer_knuckle_joint
default_q: [
    1e-04,-0.0002,0.0008,0.0002,-0.0003,0.0,0.0,-0.0,-0.0
]

# Most dimensions of the cspace have a direct corresponding element
# in the URDF. This list of rules defines how unspecified coordinates
# should be extracted or how values in the URDF should be overwritten.

cspace_to_urdf_rules:

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  - left_finger_plus:
    - "center": [-0.011, 0.002, 0.003]
      "radius": 0.002
    - "center": [-0.011, 0.002, 0.006]
      "radius": 0.002
    - "center": [-0.007, 0.002, 0.002]
      "radius": 0.002
    - "center": [-0.007, 0.002, 0.005]
      "radius": 0.002
    - "center": [-0.003, 0.002, 0.002]
      "radius": 0.002
    - "center": [-0.003, 0.002, 0.005]
      "radius": 0.002
    - "center": [-0.011, 0.003, 0.011]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.034]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.013]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.016]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.019]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.022]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.025]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.028]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.031]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.011]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.033]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.013]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.016]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.019]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.022]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.025]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.027]
      "radius": 0.001
    - "center": [-0.008, 0.003, 0.03]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.009]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.033]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.012]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.015]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.018]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.021]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.024]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.027]
      "radius": 0.001
    - "center": [-0.004, 0.003, 0.03]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.009]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.033]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.012]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.015]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.018]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.021]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.024]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.027]
      "radius": 0.001
    - "center": [-0.001, 0.003, 0.03]
      "radius": 0.001
  - right_finger_plus:
    - "center": [-0.002, 0.003, 0.011]
      "radius": 0.001
    - "center": [-0.002, 0.003, 0.033]
      "radius": 0.001
    - "center": [-0.002, 0.003, 0.013]
      "radius": 0.001
    - "center": [-0.002, 0.003, 0.016]
      "radius": 0.001
    - "center": [-0.002, 0.003, 0.019]
      "radius": 0.001
    - "center": [-0.002, 0.003, 0.022]
      "radius": 0.001
    - "center": [-0.002, 0.003, 0.025]
      "radius": 0.001
    - "center": [-0.002, 0.003, 0.028]
      "radius": 0.001
    - "center": [-0.002, 0.003, 0.031]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.011]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.034]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.013]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.016]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.019]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.022]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.025]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.028]
      "radius": 0.001
    - "center": [-0.005, 0.003, 0.031]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.011]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.034]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.013]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.016]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.019]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.022]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.025]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.028]
      "radius": 0.001
    - "center": [-0.007, 0.003, 0.031]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.011]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.034]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.013]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.016]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.019]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.022]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.025]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.028]
      "radius": 0.001
    - "center": [-0.011, 0.003, 0.031]
      "radius": 0.001
